name: Manual Mobile Release

on:
  workflow_dispatch:
    inputs:
      deploy_type:
        description: "Type of deployment: ota or build"
        required: true
        type: choice
        options:
          - ota
          - build
      release_channel:
        description: "Release channel or profile name"
        required: false
        default: "preview"
      update_message:
        description: "Custom OTA update message"
        required: false
        default: "Manual OTA update via GitHub Actions"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install eas-cli
        run: npm install -g eas-cli

      - name: Install project dependencies
        run: npm install

      - name: Run selected command
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: |
          echo "Deployment type: ${{ github.event.inputs.deploy_type }}"
          echo "Channel/profile: ${{ github.event.inputs.release_channel }}"
          echo "Update message: ${{ github.event.inputs.update_message }}"

          if [ "${{ github.event.inputs.deploy_type }}" = "ota" ]; then
            eas update --branch ${{ github.event.inputs.release_channel }} --non-interactive --message "${{ github.event.inputs.update_message }}"
          else
            eas build -p ios --profile ${{ github.event.inputs.release_channel }} --non-interactive
          fi
